# Create with `conda env create -f environment.yml`
name: nn

dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - pandas
  - opencv
  - tifffile
  - scikit-image
  - scikit-learn
  - ipykernel
  - opencv
  - cython
  - protobuf
  - absl-py
  - pyyaml
  - tqdm
  - ipywidgets
  - h5py
  - werkzeug
  - markdown
  - joblib
  - read-roi
  - pip:
    - keras
    - imgaug
    - pycocotools
    - tensorflow-gpu
    - tensorboard
    - quilt
    - https://github.com/matterport/Mask_RCNN/archive/master.zip
    - https://github.com/hadim/simuscope/archive/master.zip